# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.14.2"
gem "capybara", "3.35"
gem "cucumber", "5.3"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.10"
gem "rufo", "0.12.0"
gem "faker", "2.14"
gem "mongo", "2.13.1"
gem "httparty", "0.18.1"
